---
- hosts: all
  tasks: 
   - name: Add http proxy for internet
     lineinfile: dest=/root/.bashrc line='export http_proxy=172.30.48.178:3128' state=present
   - name: Adding https proxy for internet
     lineinfile: dest=/root/.bashrc line='export https_proxy=172.30.48.178:3128' state=present
   - name: Apply soure
     shell: source /root/.bashrc
     become_user: root