- hosts: all
  user: root
  port: 22
  gather_facts: True
  roles:
    - { role: install-docker }
  environment:
    http_proxy: 172.30.48.178:3128
    https_proxy: 172.30.48.178:3128
- hosts: docker_master
  user: root
  gather_facts: True
  roles:
    - { role: create-swarm }
  environment:
    http_proxy: 172.30.48.178:3128
    https_proxy: 172.30.48.178:3128
- hosts: docker_manager
  user: root
  gather_facts: True
  roles:
    - { role: create-swarm }
  environment:
    http_proxy: 172.30.48.178:3128
    https_proxy: 172.30.48.178:3128
- hosts: docker_worker
  user: root
  gather_facts: True
  roles:
    - { role: create-swarm }
  environment:
    http_proxy: 172.30.48.178:3128
    https_proxy: 172.30.48.178:3128