---
# tasks file for create-swarm and store tokens 
- name: Starting docker
  when: inventory_hostname in groups['docker_master']
  shell: sudo systemctl start docker

- name: Initializing docker swarm
  when: inventory_hostname in groups['docker_master']
  shell: docker swarm init | grep '\-\-token '
  register: result

- name: Debug SwarmInit
  debug:
    var: result.stdout
  
- name: Registering token with variable
  add_host:
    name: "token_host"
    token: " {{ result.stdout }}"

- name: Initializing docker swarm
  when: inventory_hostname in groups['docker_master']
  shell: docker swarm join-token manager | grep '\-\-token '
  register: result
  
- name: Ouputing manager token 
  debug:
    var: result.stdout

- name: Registering manager token with variable
  add_host:
    name: "token_host_manager"
    token: " {{ result.stdout }}"


  