---
# tasks file for install-docker
- name: Check the internet 
  shell: echo $http_proxy
  register: ping
- debug:
   var: ping
- name: remove the Apache package
  yum:
    name: [ 
            'docker',
            'docker-client',
            'docker-client-latest',
            'docker-common',
            'docker-latest',
            'docker-latest-logrotate',
            'docker-logrotate',
            'docker-engine'
          ]
    update_cache: true
    state: removed
  become: true
  register: result
- debug: 
   var: result

- name: Install prerequisites in yum
  yum:
    name: ['yum-utils','device-mapper-persistent-data','lvm2']
    update_cache: yes
  become: true

- name: Adding docker repository
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker
  yum:
    name: ['docker-ce','docker-ce-cli','containerd.io','python-pip']
    update_cache: yes
    state: present
  become: true

- name: "Increasing heap memory"
  shell: sysctl -w vm.max_map_count=262144
  become: true